version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Building project...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l target

  artifacts:
    files:
      - target/cafelog-0.0.1-SNAPSHOT.jar
    discard-paths: yes
    base-directory: target
