version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven zip

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Building project...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Packaging deployment artifacts...
      - mkdir -p deploy/scripts
      - cp -r scripts/* deploy/scripts/
      - cp appspec.yml deploy/
      - cp target/cafelog-0.0.1-SNAPSHOT.jar deploy/
      - cd deploy && zip -r ../deploy-package.zip . && cd ..
      - echo Uploading to S3...
      - aws s3 cp deploy-package.zip s3://cafelog-s3-images/

artifacts:
  files:
    - deploy-package.zip

